In [1]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
df = pd.read_csv("btcusdt_1m.csv")

In [9]:
df.head(100)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2023-12-13 00:00:00,41492.38,41506.00,41476.17,41476.18,23.92517,2023-12-13 00:00:59.999,9.927303e+05,1003,9.64939,4.004294e+05,0
1,2023-12-13 00:01:00,41476.18,41479.51,41435.13,41441.32,42.52961,2023-12-13 00:01:59.999,1.763006e+06,1254,6.92112,2.868889e+05,0
2,2023-12-13 00:02:00,41441.32,41441.33,41394.27,41394.28,78.02927,2023-12-13 00:02:59.999,3.232068e+06,1523,10.56972,4.378169e+05,0
3,2023-12-13 00:03:00,41394.27,41421.26,41394.27,41421.26,23.38614,2023-12-13 00:03:59.999,9.683890e+05,1037,13.11932,5.432206e+05,0
4,2023-12-13 00:04:00,41421.26,41430.44,41416.59,41424.95,14.50482,2023-12-13 00:04:59.999,6.008739e+05,822,4.46984,1.851637e+05,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023-12-13 01:35:00,41170.51,41184.00,41112.00,41114.16,37.86624,2023-12-13 01:35:59.999,1.557779e+06,854,11.36572,4.676071e+05,0
96,2023-12-13 01:36:00,41114.15,41126.00,41050.85,41055.63,158.46490,2023-12-13 01:36:59.999,6.508150e+06,1258,109.85663,4.511143e+06,0
97,2023-12-13 01:37:00,41055.63,41119.16,41052.46,41119.15,139.95709,2023-12-13 01:37:59.999,5.748310e+06,1691,116.85630,4.799175e+06,0
98,2023-12-13 01:38:00,41119.15,41119.16,41098.00,41099.07,32.70145,2023-12-13 01:38:59.999,1.344313e+06,589,17.90656,7.361013e+05,0
99,2023-12-13 01:39:00,41099.06,41103.55,41099.06,41103.55,7.07806,2023-12-13 01:39:59.999,2.909220e+05,365,6.19956,2.548129e+05,0